# Generated by Django 4.2.13 on 2024-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Statut"),
        ),
    ]
