# Generated by Django 4.2.13 on 2024-09-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0017_remove_productvariant_photos_supplémentaires_and_more"),
        ("rating", "0002_alter_reviewrating_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="pro_commerce.product",
            ),
        ),
    ]
