# Generated by Django 4.2.13 on 2024-07-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=40, verbose_name="Nom de la catégorie"),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Nom de la catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=40, verbose_name="Nom de la sous-catégorie"
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="souscategories",
                        to="pro_commerce.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-catégorie",
                "verbose_name_plural": "Sous-catégories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="products/", verbose_name="Photo du produit"
                    ),
                ),
                ("nom", models.CharField(max_length=40, verbose_name="Nom du produit")),
                ("ville", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(verbose_name="Description du produit"),
                ),
                ("prix", models.BigIntegerField(verbose_name="Prix du produit")),
                (
                    "stock",
                    models.BigIntegerField(verbose_name="Stock disponible du produit"),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="pro_commerce.category",
                        verbose_name="Catégorie du produit",
                    ),
                ),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="souscategorieduproduit",
                        to="pro_commerce.subcategory",
                        verbose_name="sous categorie produit",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produituser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="produit de utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ville",
                    models.CharField(max_length=40, verbose_name="Ville du vendeur"),
                ),
                (
                    "quartier",
                    models.CharField(
                        max_length=40, verbose_name="Quartier ou secteur du vendeur"
                    ),
                ),
                (
                    "repere",
                    models.CharField(
                        max_length=40, verbose_name="Point de référence du vendeur"
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produit",
                        to="pro_commerce.product",
                        verbose_name="produit",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
    ]
