# Generated by Django 4.2.13 on 2024-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
