# Generated by Django 4.2.13 on 2024-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0004_userfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="category_images/",
                verbose_name="Photo du categorie",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="sub_category_images/",
                verbose_name="Photo du sous categorie",
            ),
        ),
    ]
