# Generated by Django 4.2.13 on 2024-08-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0005_category_photo_subcategory_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adresse",
            name="produit",
        ),
        migrations.AddField(
            model_name="product",
            name="adresse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adresse",
                to="pro_commerce.adresse",
                verbose_name="adresse",
            ),
        ),
    ]
