# Generated by Django 4.2.13 on 2024-08-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0006_remove_adresse_produit_product_adresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="adresse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresse",
                to="pro_commerce.adresse",
                verbose_name="adresse",
            ),
        ),
    ]
