# Generated by Django 4.2.13 on 2024-08-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0008_reviewrating_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
