# Generated by Django 4.2.13 on 2024-09-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0011_alter_reviewrating_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="pro_commerce.product",
            ),
        ),
    ]
