# Generated by Django 4.2.13 on 2024-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0012_alter_reviewrating_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Statut"),
        ),
    ]
