# Generated by Django 4.2.13 on 2024-09-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0013_alter_reviewrating_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewrating",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="reviewrating",
            name="user",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="ReviewRating",
        ),
    ]
