# Generated by Django 4.2.13 on 2024-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pro_commerce",
            "0014_remove_reviewrating_produit_remove_reviewrating_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photos",
            field=models.URLField(
                blank=True, null=True, verbose_name="Photo du catégorie"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="photos",
            field=models.URLField(default=1, verbose_name="Photo du produit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subcategory",
            name="photos",
            field=models.URLField(
                blank=True, null=True, verbose_name="Photo du sous-catégorie"
            ),
        ),
    ]
