# Generated by Django 4.2.13 on 2024-09-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0016_productimage_alter_product_photos_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="photos_supplémentaires",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
