# Generated by Django 4.2.13 on 2024-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0017_remove_productvariant_photos_supplémentaires_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="photo_principale",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="photo_variant",
            field=models.ImageField(
                default=1,
                upload_to="product_variants/",
                verbose_name="Photo principale",
            ),
            preserve_default=False,
        ),
    ]
