# Generated by Django 4.2.13 on 2024-09-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pro_commerce", "0018_remove_productvariant_photo_principale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="couleur",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="taille",
        ),
    ]
