# Generated by Django 4.2.13 on 2024-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0002_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numero de telephone"
            ),
        ),
    ]
