# Generated by Django 4.2.13 on 2024-09-04 12:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0003_alter_user_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Numéro de téléphone",
            ),
        ),
    ]
