# Generated by Django 4.2.13 on 2024-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0005_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
