# Generated by Django 4.2.13 on 2024-09-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0006_user_otp_user_otp_expiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_expiry",
        ),
    ]
